In [1]:
#new file we are using those pickle files, assume that this is a website where user provides us the new passenger details

In [2]:
import pickle 
import numpy as np

In [3]:
# here we are decoding the pickle objects
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [4]:
# Assume user input
#Pclass/gender/age/Sibsp/parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [11]:
#here we have to apply alll the preprocessing steps we did there
# no need to imputation

test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\Gayathri\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [12]:
test_input_sex

array([[1.]])

In [13]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

c:\Users\Gayathri\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [14]:
test_input_embarked

array([[0., 0., 1., 0.]])

In [15]:
test_input_age = test_input[:,2].reshape(1,1)

In [16]:
test_input_age

array([[31.0]], dtype=object)

In [21]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [22]:
test_input_transformed.shape

(1, 10)

In [24]:
clf.predict(test_input_transformed) # this passenger died

array([0])